on:
  workflow_dispatch:

name: Run Downtimerobot

jobs:
  downtimerobot:
    name: Downtimerobot
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: run
        uses: dorianim/downtimerobot-action@latest
        
      - name: test
        run: |
          env

      - name: Deploy 🚀
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: public
