on:
  workflow_dispatch:

name: Run Downtimerobot

jobs:
  downtimerobot:
    name: Downtimerobot
    runs-on: ubuntu-22.04
    steps:
      - name: run
        uses: dorianim/downtimerobot-action@v0.0.2
